### ISSUE TITLE
Loading Profiles and cookies instead of statically setting cookie

### ISSUE THREAD

**Issue by krjii** [1220moritz/reverse-twitter-scraper#1]
Instead of the manual step for configuring the necessary cookies, developers can load an existing browser profile into the chrome driver instance.  I have experience using this approach with the gecko (firefox) selenium driver. I'm assuming it's pretty similar for chrome or other drivers.  

The profiles/cookies that can be loaded is dependent on the browser a developer has installed on their machine and uses for browsing.

Selenium documentation for configuring the driver profile can be found here: https://www.selenium.dev/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.firefox_profile.html

It's pretty simple to implement.

![image](https://github.com/1220moritz/reverse-twitter-scraper/assets/3146117/7adb3a64-13cb-478e-a32d-b61632c4100f)

**Comment by 1220moritz** [comment]
Will take a look. The scraper is currently broken so I'll try to fix it first.
But sounds like a good suggestion, thanks!

**Comment by krjii** [comment]
>

**Comment by krjii** [comment]
I might have some time to throw something together. I have the initial code in place. I think the capability has many use cases. I haven't seen any other packages to support "authenticated" sessions through selenium.

I need about a week or 2. It's vacation time with family
