### ISSUE TITLE
TypeError: WebDriver.__init__() got multiple values for argument 'options'

### ISSUE THREAD

**Issue by 0xking-sol** [1220moritz/reverse-twitter-scraper#2]
Ran into an error when trying to run the code. Might be a version compatibilty issue, sharing details here.

### Approach:

1. Copied entire cookies line and pasted into cookies = "Cookies_Pasted_Here".

<img width="217" alt="Screenshot 2023-07-04 at 11 42 41" src="https://github.com/1220moritz/reverse-twitter-scraper/assets/124360861/177bd91b-61ca-4480-b9b4-56934428426d">

2. Tried to run the example script:
```
from ReverseTwitterScraper import TwitterScraper

chromedriver_path = "C:/Program Files (x86)/chromedriver.exe"
cookies = "" #no account cookies
cookies = {'Cookie': 'your Cookie', 'X-Csrf-Token': 'your csrf token'} #with account cookie
proxy_list = []


twitter_handle = ["elonmusk"]  # single account
twitter_handles = ["elonmusk", "POTUS", "latestinspace"]  # multiple accounts
scraper = TwitterScraper(twitter_handle, chromedriver_path, cookies, proxy_list)
tweets = scraper.getTweetsText()

print(tweets)
```

3. Following errors:
TypeError: Invalid type for url.  Expected str or httpx.URL, got <class 'NoneType'>: None
TypeError: WebDriver.__init__() got multiple values for argument 'options'

### Troubleshooting:
1. Chromedriver works by itself with other scripts
3. Selenium version 4.10.0 
4. Macbook air M1, using pycharm 

Could you also please help me understand the distinction between cookie and X-Csrf-Token in the code?

Thanks!

**Comment by 1220moritz** [comment]
The account cookie and X-Csrf-Token have to match. You need to get both when you manually copy the cookie.
This is not the issue though.
Twitter requires login now to view/scrape tweets. Even if you want to use account cookies with my scraper, it tries to get the auth cookies before and just sends the "getTweets" requests with account cookies. 
I think it's currently broken and I'm trying to fix it asap.

**Comment by 0xking-sol** [comment]
Thanks for continuously working on this. 0.8 refers to your code version? 

I also wrote a simple script for exporting a user's own bookmarks which I'd be happy to add as functionality here if that would be of interest
